mazintech/mazintech/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from . import views
from django.contrib.auth import views as auth_views
from django_js_reverse.views import urls_js
from models import RegionAutoComplete,DistrictAutoComplete

urlpatterns = [
    url(r'^$', views.home, name='home'),

    url(r'^region_autocomplete/$', RegionAutoComplete.as_view(), name='region_autocomplete'),
    url(r'^district_autocomplete/$', DistrictAutoComplete.as_view(), name='district_autocomplete'),

    url(r'^jsreverse/$', urls_js, name='js_reverse'),
    url(r'^accounts/login/$', auth_views.login, name='login'),
    url(r'^accounts/signup/$', views.signup, name='signup'),
    url(r'^accounts/logout/$', auth_views.logout,{'next_page':'/'}, name='logout'),
    url(r'^about/$', views.about, name='about'),
    url(r'^users$', views.users, name='users'),
    url(r'^users/college-admins/(?P<college_administrators>\d+)/$', views.users, name='college_admins'),
    url(r'^user/add/$', views.user_edit, name='user_add'),
    url(r'^user/edit/(?P<user_id>\d+)/$', views.user_edit, name='user_edit'),

    url(r'^', include('weatherapp.urls', namespace='weatherapp')),

    url(r'^regions$', views.view_regions, name='view_regions'),
    url(r'^branches$', views.view_branches, name='view_branches'),

    url(r'^downloads/$', views.downloads_list, name="view_downloads"),
    url(r'^downloads/(?P<file_id>\d+)/$', views.file_download_task, name="file_download"),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mazintech/weatherapp/urls.py
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.contrib import admin
from dal import autocomplete

import views
# from mazintech.autocomplete import *

from .models import *
from mazintech.models import *

urlpatterns = [
    url(r'^weather_list/$', views.weather_list, name='weather_list'),
    url(r'^weather_data/$', views.save_weather_data, name='weather_data'),    
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

mazintech/mazintech/forms.py
import os

from django.conf import settings
from django import forms
from django.db.models import Q
from datetime import datetime
from django.db.models import Value as V
from django.db.models.functions import Concat
from dal import autocomplete, forward
from django.forms.widgets import *
from django.core.exceptions import ValidationError
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from models import MazintechUser, Region, Branch, Document, Address, Contact


class MazintechUserForm(forms.ModelForm):

    password1 = forms.CharField(
        required=False, label="Password (leave empty if not changed)", widget=forms.PasswordInput)
    password2 = forms.CharField(
        required=False, label="Re-enter password", widget=forms.PasswordInput)
    region = forms.ModelChoiceField(required=False,
                                    queryset=Region.objects.all(),
                                    empty_label=None,
                                    widget=autocomplete.ListSelect2(url='region_autocomplete',
                                    attrs={'data-placeholder': "---------"}
                                    ))

    district = forms.ModelChoiceField(required=False,
                                      queryset=Branch.objects.all(),
                                      empty_label=None,
                                      widget=autocomplete.ListSelect2(url='district_autocomplete',
                                      attrs={'data-placeholder': "---------"},
                                      forward=('region',)
                                      ))        
    class Meta:
        model = MazintechUser
        fields = ['first_name','last_name','username','email','phone_number',
                  'region','district','signature','groups','regional_staff',
                  'is_active']       
        widgets = {'groups': forms.CheckboxSelectMultiple()}

    def __init__(self, *args, **kwargs):
        super(MazintechUserForm, self).__init__(*args, **kwargs)
        self.fields['district'].widget.attrs['class'] = 'multi_select'
        
    def clean_password1(self):
        if not self.cleaned_data.get('password1') and not self.instance.pk:
            raise ValidationError("Please enter a password for this user")
        return self.cleaned_data.get('password1')

    def clean_password2(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')

        if password1 != password2:
            raise ValidationError("Passwords do not match")

        if not password1 and not self.instance.pk:
            raise ValidationError("Please enter a password for this user")

        return password2

    def save(self, commit=True, *args, **kwargs):
        ops_user = super(MazintechUserForm, self).save(commit=False)
        region = self.instance.region

        if self.cleaned_data.get('password1'):
            ops_user.set_password(self.cleaned_data.get('password1'))

        groups = self.cleaned_data.get('groups', [])
        district = self.cleaned_data.get('district', [])
        
        if commit:
            ops_user.save()
            ops_user.groups = groups

        return ops_user        


class MazintechUserFilterForm(forms.Form):

    name = forms.CharField(required = False)
    active = forms.ChoiceField(required = False, choices = (('', "--- Select User Status ---"), ('active', "Active"), ("inactive", "Inactive")))

    def __init__(self, *args, **kwargs):
        super(MazintechUserFilterForm, self).__init__(*args, **kwargs)

        self.fields['name'].widget.attrs['placeholder'] = 'User, Name,Email, Phon.... '

    def filter(self, users):
        if self.cleaned_data is not None:
            if self.cleaned_data['active']:
                if self.cleaned_data['active'] == 'active':
                    users = users.filter(is_active=True)
                if self.cleaned_data['active'] == 'inactive':
                    users = users.filter(is_active=False)


            if self.cleaned_data['name']:
                users = users.annotate(fullname=Concat('first_name', V(" "), 'last_name'))
                term = self.cleaned_data['name']
                users = users.filter(Q(first_name__icontains=term) |
                                     Q(last_name__icontains=term) |
                                     Q(fullname__icontains=term) |
                                     Q(email__icontains=term) |
                                     Q(phone_number__icontains=term) |
                                     Q(username__icontains=term))
          
            
        return users


class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    last_name = forms.CharField(max_length=30, required=False, help_text='Last Name Optional.')
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')

    class Meta:
        model = MazintechUser
        fields = ('username', 'first_name', 'last_name', 
                  'email', 'password1', 'password2', )

    def __init__(self, *args, **kwargs):
        super(SignUpForm, self).__init__(*args, **kwargs)

    def clean_password1(self):
        if not self.cleaned_data.get('password1') and not self.instance.pk:
            raise ValidationError("Please enter a password for this user")
        return self.cleaned_data.get('password1')

    def clean_password2(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')

        if password1 != password2:
            raise ValidationError("Passwords do not match")

        if not password1 and not self.instance.pk:
            raise ValidationError("Please enter a password for this user")

        return password2


class RegionForm(forms.ModelForm):

    class Meta:
        model = Region
        exclude = ['deleted']


class BranchForm(forms.ModelForm):

    class Meta:
        model = Branch
        exclude = ['deleted']


class DocumentFileForm(forms.ModelForm):
    description = forms.CharField(widget=forms.Textarea)
    class Meta:
        model = Document
        fields = ['document', 'description']


class PhotoFileForm(forms.ModelForm):
    
    class Meta:
        model = Document
        fields = ['image', 'description']
        

class AddressForm(forms.ModelForm):
    
    class Meta:
        model = Address
        exclude = ['deleted', 'address_type']


class ContactForm(forms.ModelForm):

    class Meta:
        model = Contact
        fields = ['first_name', 'last_name', 'tel_number', 'cell_number', 'email']


class DownloadsFilterForm(forms.Form):
    name = forms.CharField(required = False)
    start_date = forms.CharField(required=False, label='Start date')
    end_date = forms.CharField(required=False, label='End date')

    def __init__(self, *args, **kwargs):
        super(DownloadsFilterForm, self).__init__(*args, **kwargs)

        self.fields['name'].widget.attrs['placeholder'] = 'Search Downloaded By, File Name ,Desc...'
        self.fields['end_date'].widget.attrs['class'] = 'date_field'
        self.fields['start_date'].widget.attrs['class'] = 'date_field'
        self.fields['start_date'].widget.attrs['placeholder'] = 'Start Date'
        self.fields['end_date'].widget.attrs['placeholder'] = 'End Date'
        
    def filter(self, downloads):
        if self.cleaned_data is not None:
            if self.cleaned_data['name']:
                users = MazintechUser.objects.filter(username__icontains=self.cleaned_data['name']).values_list('id', flat=True)
                                                                    
                downloads = downloads.filter(Q(description__icontains=self.cleaned_data['name'])|
                                             Q(document_name__icontains=self.cleaned_data['name'])|
                                             Q(created_by__in=users))

            if self.cleaned_data['start_date']:
                    downloads = downloads.filter(created_at__gte=self.cleaned_data['start_date'])

            if self.cleaned_data['end_date']:
                    downloads = downloads.filter(created_at__lte=self.cleaned_data['end_date'])
        
        return downloads

mazintech/mazintech/views.py
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.decorators import login_required,user_passes_test
from django.contrib.auth.decorators import permission_required
from django.contrib.auth import authenticate
from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse
from django.http import HttpResponse, HttpResponseRedirect
from models import MazintechUser, Region, Branch
from forms import MazintechUserForm, MazintechUserFilterForm, RegionForm
from forms import BranchForm, DownloadsFilterForm, SignUpForm
from mazintech.models import *
from weatherapp.models import *
from lib.file_handler import file_download
import threading
import datetime
from django.contrib import messages

@login_required
def about(request): 
    return render(request, "about.html", {})

@login_required
def home(request, template='mazintech/home.html'):

    context = {}
    weather_now = Weather.objects.all().order_by('-weather_date').first()
    weather_list = Weather.objects.all().order_by('-weather_date')
    context['weather_now'] = weather_now
    context['weather_list'] = weather_list
    
    return render(request, template, context)

@login_required
@user_passes_test(lambda u: u.is_superuser) 
def users(request, college_administrators=False, template="users/users.html"):
    
    context = {}
    user_filter_form = MazintechUserFilterForm(request.POST or None)
    if college_administrators:
        users = MazintechUser.objects.filter(groups__name='College Administrators')
        title = "College Administrators"
    else:
        users = MazintechUser.objects.all()
        title = "Users"

    if not request.user.is_superuser:
        return redirect(reverse('logout'))

    if u'search' in request.POST:
        if user_filter_form.is_valid():
            users = user_filter_form.filter(users)
            if len(set(user_filter_form.cleaned_data.values())) > 1:
                context['reset_button'] = True

    
    context['users'] = users
    context['title'] = title
    context['user_filter_form'] = user_filter_form
    return render(request, template, context)

@login_required
@user_passes_test(lambda u: u.is_superuser) 
def user_edit(request, user_id=None, template="users/user_edit.html"):
    context = {}
    user = MazintechUser.objects.get(pk=user_id) if user_id else None
    user_form = MazintechUserForm(request.POST or None, instance=user)

    if not request.user.is_superuser:
        return redirect(reverse('logout'))

    if u'save' in request.POST  and  user_form.is_valid():
        user = user_form.save()
        next = request.POST.get('next', '/')
            
        return HttpResponseRedirect(next)

    if u'cancel' in request.POST:
        next = request.POST.get('next', '/')
        return HttpResponseRedirect(next)
        

    context['form'] = user_form
    context['user'] = user
    return render(request, template, context)


def signup(request, template="users/user_edit.html"):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            next = request.POST.get('next', '/')            
            return HttpResponseRedirect(next)
    else:
        form = SignUpForm()

    if u'cancel' in request.POST:
        next = request.POST.get('next', '/')
        return HttpResponseRedirect(next)
    return render(request, template, {'form': form})        


@login_required
def view_regions(request, template="mazintech/view_regions.html"):
    context = {}

    regions = Region.objects.all().order_by('code')
    
    context['regions'] = regions

    return render(request, template, context) 

@login_required
def view_branches(request, template="mazintech/view_branches.html"):
    context = {}

    branches = Branch.objects.all()
    
    context['branches'] = branches

    return render(request, template, context)


@login_required
def downloads_list(request, template="mazintech/downloads.html"):
    context = {}
   
    downloads = Document.objects.filter(file_type__in=['Download']).order_by("-created_at")
    filter_form = DownloadsFilterForm(request.POST or None)
    if u'search' in request.POST:
        if filter_form.is_valid():
            downloads = filter_form.filter(downloads)

    context['downloads'] = downloads
    context['dl_user'] = request.user
    context['filter_form'] = filter_form

    return render(request, template, context)


def file_download_task(request, file_id):
    saved_file = Document.objects.get(pk=file_id)
    return file_download(file=saved_file)

mazintech/templates/mazintech/_downloads_filter.html
{% load bootstrap4 %}

<div class="row">  
    <input name="filter" type="hidden"> 
  <div class="col-lg-3 pull-right">      
    <div class='pull-right'>
      <button type="submit" name="search" class="btn btn-primary" title="Search"><i class="fa fa-search"></i> Search</button>
      <a href="."  class="btn btn-primary" title="Clear Search"><i class="fa fa-search-minus"></i> Clear</a>       
    </div>

  </div>
  <div class="col-lg-9"> 
    {% for field in filter_form %}
      <div class='col-lg-3'>
        {% bootstrap_field field layout='inline' %}
      </div>
    {% endfor %}
     <label style="margin-left: 60px; margin-top: 7px;" class="switch">
        <span class="switch_label">Show All</span>
        <input onchange="vehicle.toggle_downloads_list();" type="checkbox">
        <div class="slider round"></div>
      </label>      
       
  </div>
</div>

mazintech/templates/mazintech/_list_branches.html
{% load el_pagination_tags %}
<table id="" class="table table-hover ">
  <tr>
    <th>District Code</th>
    <th>District Desciption</th>
    <th>Region</th>
  </tr>

  {% paginate branches %}
  {% for branch in branches %}

  <tr>   
    <td>{{ branch.code }}</td>
    <td>{{ branch.description }}</td>
    <td>{{ branch.region.name }}</td>
  </tr>
  {% endfor %}
  <tr>
    <td colspan='13' style="text-align: center">
    <div class="center">
      <div class="pagination">
        {% show_pages %}
      </div>
    </div>
    </td>
  </tr>
</table>

mazintech/templates/mazintech/_list_downloads.html
{% load el_pagination_tags %}
    <!-- Rounded switch -->
          
    {% paginate downloads %}
    <table id="gridtable" class="table table-hover downloads_table">
      <thead>
        <th>Download Date</th>
        <th>Downloaded By</th>
        <th>Description</th>
        <th>File Name</th>
        <th class="text-align-center">Download</th>
      <tbody>
        {% for download in downloads %}
        <tr class="{% cycle 'even_row' 'odd_row' %} {% if download.created_by.id == dl_user.id %}dl_user{% else %}hidden{% endif %}" >
          <td>{{ download.created_at }}</td>
          <td>{{ download.created_by.full_name }}</td>
          <td>{{ download.description }}</td>
          <td>{{ download.document.name }}</td>
          <td class="text-align-center">
            <a title="Download" href="{% url 'file_download' download.id %}">
              <i class="fa fa-download" aria-hidden="true"></i>
            </a>
          </td>
        </tr>
        {%endfor%}
      </tbody>
    </table>
    <div class="text-align-center">
      <div class="pagination">
        {% show_pages %}
      </div>
    </div>
  

mazintech/templates/mazintech/_list_regions.html
{% load el_pagination_tags %}
<table id="" class="table table-hover ">
  <tr>
    <th>Region Code</th>
    <th>Region Name</th>   
    <th></th>
  </tr>

  {% paginate regions %}
  {% for region in regions %}

  <tr>   
    <td>{{ region.code }}</td>
    <td>{{ region.name }}</td> 
    <td></td>   
  </tr>
  {% endfor %}
  <tr>
    <td colspan='13' style="text-align: center">
    <div class="center">
      <div class="pagination">
        {% show_pages %}
      </div>
    </div>
    </td>
  </tr>
</table>

mazintech/templates/mazintech/_list_tickets.html
{% load el_pagination_tags %}
<table id="" class="table table-hover ">
  <tr>
    <th>Ticket Number</th>
    <th>Created By</th>
    <th>Status</th>
    <th>Subject</th>
    <th>Category</th>
    <th>Technician</th>  
    <th>Created Date</th>     
  </tr>

  {% paginate tickets %}
  {% for ticket in tickets %}

  <tr>   
    <td>
      <a href="{% url 'edit_ticket' ticket.id %}" data-toggle="" data-toggle="tooltip" data-placement="right" title="Edit Ticket">
        <i class="fas fa-pencil-alt" aria-hidden="true"></i>  {{ ticket.number }}</a>
    </td>
    <td>{{ ticket.created_by }} </td> 
    <td>{{ ticket.status }}</td> 
    <td>{{ ticket.subject }} </td>
    <td>{{ ticket.category |title }} </td>
    <td>{{ ticket.technician | default_if_none:"Unassigned" }} </td>  
    <td>{{ ticket.created_at | date:"d M Y" }} </td>  
     
  </tr>
  {% endfor %}
  <tr>
    <td colspan='13' style="text-align: center">
    <div class="center">
      <div class="pagination">
        {% show_pages %}
      </div>
    </div>
    </td>
  </tr>
</table>

mazintech/templates/mazintech/district_uploads.html
{% extends "base.html" %}
{% load staticfiles %}
{% load bootstrap4 %}
{% load humanize %}

{% block content%}
<div class="panel panel-primary transparency">
  <div class="panel-heading">
    <b>Upload Districts</b>
  </div>
  
  <div class="panel-body">
    <form method='post' enctype="multipart/form-data">
      {% csrf_token %}
      {% bootstrap_form form %}
      <br>
      <button class="btn btn-primary pull-right">Update Districts</button>
    </form>
  </div>
</div>
{% endblock %}

mazintech/templates/mazintech/downloads.html
{% extends "base.html" %}
{% load staticfiles%}
{% load bootstrap4 %}
{% load humanize %}
{% block javascript %}
  <script src="{% static 'js/vehicles.js' %}"></script>
{% endblock %}

{% block content%}

<div class="panel panel-primary transparency">
  <div class="panel-heading">
    <b>Downloads</b>
  </div>
  <div class="panel-body"> 
    <form id="insurer_filter_form" method="POST">
      {% csrf_token %}
      {% include 'mazintech/_downloads_filter.html' %}
      <div class="tab-content">
        <div id="downloads" class="tab-pane fade in active">
          {% include 'mazintech/_list_downloads.html' %}
        </div>
      </div>
    </form>
  </div>
</div>
{% endblock %}

mazintech/templates/mazintech/edit_ticket.html
{% extends "base.html" %}
{% load staticfiles %}

{% load bootstrap4 %}
{% load humanize %}
{% block content%}

<div class="panel panel-primary transparency">
  <div class="panel-heading">
    <b>{% if ticket %}Edit Ticket:{% else %}Add New Ticket{% endif %}</b>
  </div>
  
  <div class="panel-body">
    
    <form method="POST" class="form-2" novalidate>
      {% csrf_token %}
      
      <div id="edit_ticket_tab_content" class="tab-content">
        <div class="tab-pane fade active in" id="details">
          <br>
          <!-- {% for field in form %}
          <div class='col-lg-6'>{% bootstrap_field field %}</div>
          {% endfor %} -->
          <div class='col-lg-6'>{% bootstrap_field form.category %}</div>
          <div class='col-lg-6'>{% bootstrap_field form.subject %}</div>
          <div class='col-lg-6'>{% bootstrap_field form.description %}</div>
        </div>        
      </div>

      <div class="btn-group-horizontal col-lg-12">
        <div class='pull-right'>
          <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#saveModal">
            <i class='fa fa-floppy-o'></i> Save
          </button>
          <a href="{% url 'view_tickets' %}" class="btn btn-primary">
            <i class='fa fa-undo'></i> Cancel
          </a>
        </div>
      </div>
      

      <!-- Modal -->
      {% if not ticket %}
      <div class="modal fade" id="saveModal" tabindex="-1" role="dialog" aria-labelledby="saveModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h4 class="modal-title" id="saveModalLabel">Create A Ticket</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
              Are you sure you want to create a ticket?
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
              <button type="submit" class="btn btn-primary">Create</button>
            </div>
          </div>
        </div>
      </div>
      {% endif %}

      {% if ticket %}
      <div class="modal fade" id="saveModal" tabindex="-1" role="dialog" aria-labelledby="saveModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h4 class="modal-title" id="saveModalLabel">Update A Ticket</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
              Are you sure you want to update a ticket?
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
              <button type="submit" class="btn btn-primary">Update</button>
            </div>
          </div>
        </div>
      </div>
      {% endif %}
      
    </form>
  </div>
</div>

{% endblock %}

mazintech/templates/mazintech/home.html
{% extends "base.html" %}
{% load staticfiles%}
{% load humanize %}
{% block javascript %}
  <script src="{% static 'js/Chart.min.js' %}"></script>
 
</script>

{% endblock %}
<style>

{% block style %}
  
{% endblock %}

</style>



{% block content%}

{% if user.is_mazintech_employee %}

<div class="alert alert-danger alert-dismissable">
  <a href="{% url 'logout' %}" class="close" data-dismiss="alert" aria-label="close">×</a>
  <i class="fa fa-exclamation-triangle"></i> <b>Your user profile does not have enough permisions to view this section of the system. Please contact the administrator !!!</b>
</div>

{% else %}


{% endif %}
    <div class="jumbotron row">
      <div class="col-sm-12">
        <h1 class="display-4">Today's Weather Forecast!</h1>
        <p class="lead">Most recent update of your local Weather from News24. </p>
        <span class="btn btn-success btn-lg">Min Temp: {{weather_now.min_temp}}</span>
        <span class="btn btn-danger btn-lg">Max Temp: {{weather_now.max_temp}}</span>
        <span class="btn btn-primary btn-lg">Rainfall: {{weather_now.rain}}</span>
        <span class="btn btn-warning btn-lg">Wind: {{weather_now.wind}}</span>
      </div>
    </div>

    <div class="panel panel-primary transparency">
  <div class="panel-heading">
    <b>Weather Schedule</b>
    <a href="{% url 'weatherapp:weather_data' %}" class="btn btn-warning btn-xs pull-right">Load</a>
  </div>
  <div class="panel-body">
    <div class="tab-content">      
      <div class="tab-pane fade in active">
        {% include 'weather/_weather_list.html' %}
      </div>
    </div>

  </div>
</div>
    
{% endblock %}

mazintech/templates/mazintech/view_branches.html
{% extends "base.html" %}
{% load staticfiles%}
{% load bootstrap4 %}
{% load humanize %}

{% block content%}

<div class="panel panel-primary transparency">
  <div class="panel-heading">
    <b>Districts</b>
  </div>
  <div class="panel-body">
    <div class="tab-content">
      <div class="row">
        <input name="filter" type="hidden">
          <div class="col-lg-3 pull-right">
            <div class='pull-right'>
               <a href="{% url 'district_uploads' %}" class="btn btn-primary" title="Upload District(s)"><i class="fa fa-upload" aria-hidden="true"></i> Import</a>
            </div>
         </div>
    </div><br>
      <div id="traffic_fines" class="tab-pane fade in active">
        {% include 'operations/_list_branches.html' %}
      </div>
    </div>

  </div>
</div>
{% endblock %}

mazintech/templates/mazintech/view_regions.html
{% extends "base.html" %}
{% load staticfiles%}
{% load bootstrap4 %}
{% load humanize %}

{% block content%}

<div class="panel panel-primary transparency">
  <div class="panel-heading">
    <b>Regions</b>
  </div>
  <div class="panel-body">
    <div class="tab-content">
      <div id="traffic_fines" class="tab-pane fade in active">
        {% include 'operations/_list_regions.html' %}
      </div>
    </div>

  </div>
</div>
{% endblock %}

mazintech/templates/mazintech/view_tickets.html
{% extends "base.html" %}
{% load staticfiles%}
{% load bootstrap4 %}
{% load humanize %}

{% block content%}

<div class="panel panel-primary transparency">
  <div class="panel-heading">
    <b>Tickets</b>
  </div>
  <div class="panel-body">
    <form id="insurer_filter_form" method="POST">
    {% csrf_token %}

    {% include 'operations/widgets/_tickets_filter.html' %}
    
       
    <div class="tab-content">
      <div id="activeusers" class="tab-pane fade in active">
        {% include 'operations/_list_tickets.html' %}
      </div>      
    </div>

    <div class="modal fade" id="extract_modal" tabindex="-1" role="dialog" aria-labelledby="modalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="modalLabel"><i class="fa fa-info-circle" aria-hidden="true"></i> Extract Tickets</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
              <b> Are you sure you want to download the extract</b>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
              <button type="submit" name="extract" id="extract" class="btn btn-primary">Ok</button>
            </div>
          </div>
        </div>
    </div>
  </form>
  </div>
</div>
{% endblock %}