mazintech/mazintech/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from . import views
from django.contrib.auth import views as auth_views
from django_js_reverse.views import urls_js
from models import RegionAutoComplete,DistrictAutoComplete

urlpatterns = [
    url(r'^$', views.home, name='home'),

    url(r'^region_autocomplete/$', RegionAutoComplete.as_view(), name='region_autocomplete'),
    url(r'^district_autocomplete/$', DistrictAutoComplete.as_view(), name='district_autocomplete'),

    url(r'^jsreverse/$', urls_js, name='js_reverse'),
    url(r'^accounts/login/$', auth_views.login, name='login'),
    url(r'^accounts/signup/$', views.signup, name='signup'),
    url(r'^accounts/logout/$', auth_views.logout,{'next_page':'/'}, name='logout'),
    url(r'^about/$', views.about, name='about'),
    url(r'^users$', views.users, name='users'),
    url(r'^users/college-admins/(?P<college_administrators>\d+)/$', views.users, name='college_admins'),
    url(r'^user/add/$', views.user_edit, name='user_add'),
    url(r'^user/edit/(?P<user_id>\d+)/$', views.user_edit, name='user_edit'),

    url(r'^', include('weatherapp.urls', namespace='weatherapp')),

    url(r'^regions$', views.view_regions, name='view_regions'),
    url(r'^branches$', views.view_branches, name='view_branches'),

    url(r'^downloads/$', views.downloads_list, name="view_downloads"),
    url(r'^downloads/(?P<file_id>\d+)/$', views.file_download_task, name="file_download"),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mazintech/weatherapp/urls.py
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.contrib import admin
from dal import autocomplete

import views
# from mazintech.autocomplete import *

from .models import *
from mazintech.models import *

urlpatterns = [
    url(r'^weather_list/$', views.weather_list, name='weather_list'),
    url(r'^weather_data/$', views.save_weather_data, name='weather_data'),    
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

mazintech/templates/weather/_weather_list.html
{% load el_pagination_tags %}
<table id="" class="table table-hover ">
  <tr>
    <th>Date</th>
    <th>Min Temp</th>
    <th>Max Temp</th>
    <th>Wind</th>
    <th>Rain</th>
  </tr>

  {% paginate weather_list %}
  {% for weather in weather_list %}

  <tr id=row_{{weather.id}}>   
    <td>{{ weather.weather_date}}</td> 
    <td>{{ weather.min_temp|default_if_none:"" }}</td> 
    <td>{{ weather.max_temp|default_if_none:"" }}</td>
    <td>{{ weather.wind|default_if_none:"" }}</td>
    <td>{{ weather.rain|default_if_none:"" }}</td>
  </tr>
  {% endfor %}
  <tr>
    <td colspan='13' style="text-align: center">
    <div class="center">
      <div class="pagination">
        {% show_pages %}
      </div>
    </div>
    </td>
  </tr>
</table>

mazintech/templates/weather/weather.html
{% extends "base.html" %}
{% load staticfiles%}
{% load bootstrap4 %}
{% load humanize %}
{% block javascript %}
  <script src="{% static 'js/custom.js' %}"></script>
{% endblock %}

{% block content%}

<div class="panel panel-primary transparency">
  <div class="panel-heading">
    <b>Weather Forecast</b>
    
  </div> 
  <div class="panel-body">

    <form id="weather_filter_form" method="GET">
    <div class="row">
        <input name="filter" type="hidden">
        
        <div class='col-lg-3 pull-right'>
          <div class='pull-right'>
            <button type="submit" name="search" class="btn btn-primary" title="Search"><i class="fa fa-search"></i> Search</button>
            
            <a href="{% url 'weatherapp:weather_list' %}"  class="btn btn-primary" title="Clear Search"><i class="fa fa-search-minus"></i> Clear</a>
          </div>
        </div>
        
      <div class='col-lg-9'>
        <div class='col-lg-3'>
          {% bootstrap_field weather_filter_form.date_from layout='inline' %}
        </div>
        <div class='col-lg-3'>
          {% bootstrap_field weather_filter_form.date_to layout='inline' %}
        </div>

        <div class='col-lg-3'>
        </div>
    
      </div> 
    </div>
    
    <div class="tab-content">
      <div id="course" class="tab-pane fade in active">
        {% include 'weather/_weather_list.html' %}

      </div>
    </div>

    <div class="modal fade" id="extract_modal" tabindex="-1" role="dialog" aria-labelledby="modalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="modalLabel"><i class="fa fa-info-circle" aria-hidden="true"></i> Extract Course(s)</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
              <b> Are you sure you want to download the extract</b>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
              <button type="submit" name="extract" id="extract" class="btn btn-primary">Ok</button>
            </div>
          </div>
        </div>     
    </div>
  </form>
  </div>
</div>
{% endblock %}